### ISSUE TITLE
Quiz answers are case-sensitive, not user-friendly.

### ISSUE THREAD

**Issue by SamXop123** [CodewithAsh10/Quiz-Demo#1]
The current code in the quiz does not consider type cases of user. For example, if the correct answer is "A" and the user inputs "a", it is marked as incorrect. This makes the quiz less user-friendly.

The input should be case insensitive so that "A" and "a" are treated as the same answer.

Suggestion: Update the code to make the input case insensitive. for eg:
if a.upper() == "D":

Hope that helps 
Thanks

**Comment by CodewithAsh10** [comment]
<h3>Thank you Sam for pointing this issue. I highly appreciate your observation.</h3>
